### ISSUE TITLE
Ability to untrack single solves (instead of whole rooms)

### ISSUE THREAD

**Issue by big213** [Kubiverse/Cube-Zone#3]
Requsted by Iurig on discord

**Comment by Iurig** [comment]
Just elaborating on the reason: Sometimes I do single solves for fun on sessions, and from my experience, other people do that too.
Sometimes the scramble is a google CFOP scramble (I'm not a CFOP user) and I just do CFOP to see what I can get. Sometimes I change from OH to 2H or vice versa depending on the people on the room (don't wanna be a nuisance by being unnecessarily slow). Sometimes I DNF because I started inspection before scrambling. Sometimes I accidentaly submit times without a +2 when they were +2s just because the submiting motion is muscle memory.
I wouldn't wanna have to untrack the whole room for these few messups.

**Comment by big213** [comment]
Can use updateSolve() `is_tracked: false` for this apparently, so we shall be implementing this on FE soon!
